### ISSUE TITLE
KeyError: 'customerName'

### ISSUE THREAD

**Issue by diivious** [CiscoSteve/DataMiner#1]
python3 '.\Data Miner v1.0.0.15.py'
******************************************************************
****************** CISCO PX Cloud Data Miner *********************
******************************************************************
Config.ini file was found, continuing...
Start Time: 2023-07-19 09:37:36.421760
Execution: 1 of 1
Debug level is: Low
Version is 1.0.0.15
Environment is Production
Saving data in JSON and CSV formats

Getting PX Cloud Token
Done!
====================
.
.
.
Saving outputjson/Customers_Page_1_of_1.json

Search Completed!
====================

******************************************************************
****************** Running Contract Report ***********************
******************************************************************
Searching ......

.
.
.
Traceback (most recent call last):
  File "D:\Projects\DataMiner\Data Miner v1.0.0.15.py", line 6006, in <module>
    get_pxc_contracts()  # requires CSV data from get_pxc_customers
  File "D:\Projects\DataMiner\Data Miner v1.0.0.15.py", line 692, in get_pxc_contracts
    customerNameTemp = str(item['customerName'].replace('"', ','))
KeyError: 'customerName'

**Comment by diivious** [comment]
I see this in multiple versions, so its not new to the code.  Guessing there is some change to the data being returned from Cisco.  It finds about 18 contracts, then dies (reliably) on the 19th one.    Let me know what other date you would like me to provide

**Comment by PythonAPICoder** [comment]
Unfortunately, yes Cisco changed a behavior and there are instances where the key/value pair customerName is not returned. I have already started a dialog with BU to know if this is intended or a defect. If your project is on a critical timeline, i can post a workaround. I was hoping to get an official answer on this to know how to properly handle this event.

**Comment by diivious** [comment]
Yes, that would be helpful - if you want, you can share here and i can patch locally.

**Comment by PythonAPICoder** [comment]
I see two solutions when key/value is not returned for customerName:
1. Skip the record completely
2. Replace customerName with ‘N/A’ and process the remaining data

I'm waiting for BU to let me know which is the recommended path. Once i know this, i'll post a beta .16 until a formal answer is given.

**Comment by PythonAPICoder** [comment]
i posted a beta fix using option 2. let me know if this causes any other issues.

**Comment by diivious** [comment]
python3 '.\Data Miner v1.0.0.16.py'
******************************************************************
****************** CISCO PX Cloud Data Miner *********************
******************************************************************
Config.ini file was found, continuing...
Traceback (most recent call last):
  File "D:\Projects\DataMiner\Data Miner v1.0.0.16.py", line 5945, in <module>
    load_config()
  File "D:\Projects\DataMiner\Data Miner v1.0.0.16.py", line 371, in load_config
    log_to_file = int(config['settings']["log_to_file"])
ValueError: invalid literal for int() with base 10: 'False'

**Comment by PythonAPICoder** [comment]
Sorry about that, please rename your configuration file and re-run the script to create a new configuration file. I had to make some changes in the boolean values to use 0 or 1 instead of true and false due to the variety of mis-spellings. once the new configuration file is created, add your creds back into the new file.

**Comment by diivious** [comment]
OK, its working.  I have not looked at the data - but no crashes, Closing ticket .
