### ISSUE TITLE
Contracts and ContractsWithNames are creating empty JSON files

### ISSUE THREAD

**Issue by PythonAPICoder** [CiscoSteve/DataMiner#5]
User discovers the code is failing because Contracts and ContractsWithNames JSON files are being created empty. Need to add the needed dump json call to properly create the files. CSV Files are not affected.

This will be resolved in ver 1.0.0.17

**Comment by diivious** [comment]
I have a pull request open for 2 issues.  can you please look at them?

**Comment by ghost** [comment]
I believe this issue is resolved and i posted .17 with those fixes.

I have to admit, i am fairly new to GitHub so if i didnt respond to this correctly, i apologies
